name: SEO Community
description: Connecting and Advancing SEO
url: https://seo-community.org
permalink: /articles/:title
plugins:
  - jekyll-redirect-from
collections:
  conferences:
    output: true
    permalink: /conferences/:path
sass:
    style: compressed